### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by sirex** [evmorov/lang-compare#4]
What should be shown in code examples under [Constant](http://evmorov.github.io/lang-compare/ruby-python3/#other_structure_constant) and [Constant list](http://evmorov.github.io/lang-compare/ruby-python3/#other_structure_constant_list) sections?

Python does not have such thing as constant, but have [a naming convention](https://www.python.org/dev/peps/pep-0008/#constants) for variables that supposed to be used as constants.

Can I add example with python constants using conventional approach, rather than real constants?

**Comment by evmorov** [comment]
I've changed a bit the examples for Constant http://evmorov.github.io/lang-compare/ruby-coffeescript/#other_structure_constant. Now I'm making an attempt to change a constant.

Result:
- Ruby shows a warning but lets to change the var
- CoffeeScript doesn't show a warning (or maybe I should turn it on?) but doesn't let to change the var
- Java gives you an error on compilation phase
- PHP shows a warning and doesn't let to change the var

For me, this project isn't a full language reference but more a rather small cheat sheet to refresh my knowledge when I need to write something in a language that I don't use often.

What I want to say that there is no dogma. I don't know Python but if you think that it can be useful to provide an example for you and for other people and will not insult anyone - do it. Also, if people use such constants in real projects it's another reason to add it.

**Comment by sirex** [comment]
Added constants in #6.
