### ISSUE TITLE
Kotlin language support

### ISSUE THREAD

**Issue by mkdika** [evmorov/lang-compare#8]
Hi, I am planning to contribute the Kotlin language section.
May I? or there is someone else doing this?

**Comment by evmorov** [comment]
Sorry. Missed the message.
Sure, you can add it. There are no updates to the repo, but I use it when I forget how to do something. Really useful in day to day programming activities.

**Comment by evmorov** [comment]
Support has been added with the help of ChatGPT – https://evmorov.github.io/lang-compare/ruby-kotlin/. It's not complete yet, and further modifications and fixes are still necessary.
